class HomePage_Locator {
    constructor() {
        this.LOGO_HEADER = '.panel.header [aria-label="store logo"]';
        this.PRODUCT_CATEGORIES = '.level0.nav-2.category-item.level-top.parent.ui-menu-item';
        this.CATEGORIES_LIST = '[class*="level1 nav-1-"]';
        this.SIGNUP_LINK = 'ul[class="header links"] a[href$="/customer/account/create/"]';
        this.COUNTRYSTORE_IMG = '(//img[contains(@src,"flagImage")]/parent::a[contains(@href,"#")])[1]';
        this.SIGN_LINK = 'div.panel.header a[href*="customer/account/login"]';
        this.SETUP_AUTOPAY_LINK = 'a.setup-cta';
        this.COOKIE_BANNER = '//div[@id="truste-consent-track"]';
        this.COOKIE_CONSENT_BUTTON = '#truste-consent-button';
        this.COOKIE_PREFERENCE_BUTTON = '//button[@id="truste-show-consent"]';
        this.COOKIE_POLICY_LINK = 'a.truste-cookie-link';
        this.PRODUCT_CATEGORIESLINK = '.level0.nav-1.category-item.level-top.parent';
        this.PRODUCT_CATEGORIES_PROD_LINK = '.level0.nav-2.category-item.level-top';
        this.INDUSTRIES_LINK = '//a/span[text()="Industries"]';
        this.INDUSTRIES_LINK_EMEA = 'a[href*="/industries"]';
        this.SUPPLIERS_LINK = 'a[href*="/our-suppliers/"]';
        this.INNOVATION_LINK = '//a/span[text()="Innovation"]';
        this.SERVICES_LINK = '//a/span[text()="Services"]';
        this.ORDERHISTORY_FOTTER = '.links__history';
        this.QUOTEDPRODUCTS_FOTTER = '.links__quotes';
        this.CAREER_FOTTER = '.links__hiring';
        this.FOOTER_PRODUCT_CATEGORIES = '[class="footer__content"] [href*="prod"]';
        this.FOOTER_SAFETY = '[class="footer__content"] div:nth-child(2) a';
        this.FOOTER_ABOUT_US = '[class="footer__content"] div:nth-child(3) a';
        this.FOOTER_GET_IN_TOUCH = '[class="footer__content"] div:nth-child(4) a';
        this.FOOTER_COPYRIGHT = '.footer__copyright a[href]';
        this.CONTACTUS_HEADER = '.contact-link.contact-modal-trigger';
        this.SEARCHBOX = '//input[@id="search"]';
        this.ORDERHISTORY_SECTION = '.link a[href*="/order/history/"]';
        this.QUOTEDPRODUCT_SECTION = '.link a[href$="hasprice=yes"]';
        this.DISCOVERPRODUCT_SECTION = '.link a[href*="hasprice=yesno"]';
        this.IMMEDIATE_PRICING_SECTION_PREVIOUSBUTTON = '//h1[contains(text(),"Buy now with immediate pricing")]/parent::div/div/div/div/button[contains(text(),"Previous")]';
        this.IMMEDIATE_PRICING_SECTION_NEXTBUTTON = '//h1[contains(text(),"Buy now with immediate pricing")]/parent::div/div/div/div/button[contains(text(),"Next")]';
        this.DIVERSE_INDUSTRIES_SECTION_PREVIOUSBUTTON = '//h1[contains(text(),"Adding value across diverse industries")]/parent::div/div/div/div/button[contains(text(),"Previous")]';
        this.DIVERSE_INDUSTRIES_SECTION_NEXTBUTTON = '//h1[contains(text(),"Adding value across diverse industries")]/parent::div/div/div/div/button[contains(text(),"Next")]';
        this.LOGIN_MODAL = '.modal-popup.login-modal._show';
        this.LOGIN_MODAL_CLOSE = '.modal-popup.login-modal._show .action-close';
        this. IMMEDIATE_PRICING_SECTION_PRODUCT = '.product_carousel_click_webprice';
        this. IMMEDIATE_PRICING_SECTION_PRODUCT_NAME = '(//a[@class="product_carousel_click_webprice"])[1]';
        this.CAREER_LINK_HEADER = '//div[@class="header content"]/div/a';
        this.PROFILE = '.customer-welcome.active a[href$="customer/account/"]';
        this.FIRSTNAME = '(//label/following-sibling::p)[1]';
        this.LASTNAME = '(//label/following-sibling::p)[2]';
        this.PHONE = '(//label/following-sibling::p)[3]';
        this.INVOICES_LINK = 'li.invoice-link a';
        this.EMAIL = '(//label/following-sibling::p)[4]';
        this.FIRSTNAME_LABEL = '(//div[@class="customer-info__content"]/div/label)[1]';
        this.LASTNAME_LABEL = '(//div[@class="customer-info__content"]/div/label)[2]';
        this.PHONE_LABEL = '(//div[@class="customer-info__content"]/div/label)[3]';
        this.EMAIL_LABEL = '(//div[@class="customer-info__content"]/div/label)[4]';
        this.PASSWORD_RESET = '//button[@class="button button--alt reset-password-link"]';
        this.CURRENT_PASSWORD = '//input[@name="current_password"]';
        this.NEW_PASSWORD = '//input[@id="password"]';
        this.PASSWORD_CONF = '//input[@id="password-confirmation"]';
        this.PASSWORD_SAVE = '(//button[@class="action save primary button button--primary"])[2]';
        this.PASSWORD_CONFIRMATION_MESSAGE = '//div[@class="container"]';
        this.FOOTER_ABOUT_US_LINK = 'ul.footer.links a[href*="/about-us/"]';
        this.ACTIVATE_PRODUCT_CATEGORIES = '.level0.nav-1.category-item.level-top.parent.ui-menu-item.active';
        this.PRODUCT_CATALOG_LOGIN = '.level0.nav-1.category-item.first.level-top.ui-menu-item';
        this.ORDER_HISTORY_LINK = '.ph-links a[href*="/order/history/"]';
        this.FILTER_CATEGORY = '.filter-level-two__content';
        this.BROWSE_BY_CATEGORY = '.browse-by-category';
        this.COOKIE_PREFERENCE_FOOTER = '#teconsent .truste_cursor_pointer';
        this.COOKIE_PREFERENCE_MODEL = '.truste_popframe';
        this.COOKIE_PREFERENCE_CLOSE_BTN = '.truste-close-button-container';
        this.AUTOPAY_LINK = 'a.setup-cta';
        this.GO_TO_ACCOUNT = 'aside.modal-popup.canceled-modal.modal-slide._show footer button.button.button--primary';
        this.MANAGE_AUTOPAY_BUTTON = '//a[@class="action button button--alt"]';
        this.CONTACT_US_FOOTER = '.footer.links a[href*="/contact-us"]';
    }
}

module.exports = new HomePage_Locator();
