class ProductCatlogPage_Locator {
    constructor() {
        this.QUOTED_PRODUCTS_TAB_ACTIVE = '//a[@id="tab-label-products-tab-value-yes-title"]';
        this.ALL_PRODUCTS_TAB = '//a[@id="tab-label-products-tab-value-yesno-title"]';
        this.FILTERS_HEADER = '//strong[@data-role="title"]/i[@class="far fa-filter"]';
        this.RESET_FILTER = '//a[@class = "reset-filters"]';
        this.SORT_BY_FILTER = '(//label[@class="sorter-label"][contains(text(),"Sort By")]/../..//select[@id="sorter"])[1]';
        this.ALL_PRODUCT_COUNT = '(//span[@class="toolbar-number"])[last()]';
        this.REQUEST_QUOTE_BUTTON = '(//button[@class="action request_quote button button--alt request-quote"])[%s]';
        this.REQUEST_QUOTE_BUTTON_EMEA = '(//button[@class="action request_quote button button--alt request-quote"])[%s]';
        this.SUCCESSMESSAGE = 'div.container';
        this.CONTACT_US_BUTTON = '//span[@data-element="link_text"]';
        this.ADD_TO_CAART_BUTTON = '(//button[@class="action tocart button button--alt add-to-cart signed-in"])[%s]';
        this.VIEW_CART_BUTTON_ON_TOAST_MESSAGE = '//div[@class="container"]/a';
        this.PRODUCT_NAME = '(//a[@class="product-item-link product-name"])[%p]';
        this.PRODUCT_PRICE = '(//li[@class="product-item-price"]/span[@class="price"])[%s]';
        this.PRODUCT_CATALOG_TEXT = '//h1[@class="category-info__name"]';
        this.BREADCRUMB = '(//ul[@class="items"]/li)[last()]/strong';
        this.STARTING_COUNT_PRODUCTS = '(//p[@class="toolbar-amount"]/span[@class="toolbar-number"][1])[last()]';
        this.ENDING_COUNT_PRODUCTS = '(//p[@class="toolbar-amount"]/span[@class="toolbar-number"][2])[last()]';
        this.VIEW_PRICE_OR_REQUEST_QUOTE_BUTTON = '.action.guest-request-quote.button.button--alt.request-quote-guest';
        this.REQUEST_QUOTE_LINK = 'span.request-quote-label';
        this.REQUEST_QUOTE_WITHOUT_SIGNIN_BUTTON = '.modal-popup.centered-modal.login-modal.guest-modal._show .modal-footer .button.button--alt';
        this.RFQ_FORM_FIRST_NAME = '//input[@id="firstname"]';
        this.RFQ_FORM_LAST_NAME = '//input[@id="lastname"]';
        this.RFQ_PHONE_NUMBER = '//input[@id="phone"]';
        this.RFQ_EMAIL_ID = '//div[@class="field required"]/input[@id="email"]';
        this.RFQ_COMPANY_NAME = '//input[@class="input-text required-entry"][@id="company"]';
        this.RFQ_END_MARKET = '//select[@id="end-market"]';
        this.RFQ_COUNTRY = '.modal-popup.quote-request-modal-popup.centered-modal._show #country';
        this.RFQ_REGION = '//select[@id="region_id"]';
        this.RFQ_VOLUME_NEEDED = '#volume';
        this.RFQ_RADIO_BUTTON = '//label[@for="%s"]/span[@class="checkmark"]';
        this.CHEMCARE_RFQ_NO_BUTTON = 'input#no + span';
        this.RFQ_ACCOUNT_NUMBER = '//input[@id="account-number"]';
        this.TERMS_OF_USE_CHECKBOX = '//label[@for="terms-of-use"]';
        this.PRIVACY_POLICY_CHECKBOX = '//label[@for="privacy"]';
        this.SUBMIT_QUOTE_REQUEST = '.button.button--primary.submit-rfq';
        this.ALL_PRODUCT_GRID = '//div[@data-container="product-grid"]';
        this.SUPPLIEDBYFILTER = '//div[text()="Supplied By"]';
        this.GRADEFILTER = '//div[text()="Grade"]';
        this.PACKAGETYPEFILTER = '//div[text()="Package Type"]';
        this.SELECTEDFILTER = 'div.selected-filter';
        this.REMOVEFILTER_SELECTED = 'a.amshopby-remove';
        this.FILTERRESULT_PRODUCTNAME = '(//ul[@class="details-list"]/li/a)[1]';
        this.CERTIFICATIONFILTER = '//div[text()="Certification"]';
        this.FORMFILTER = '//div[text()="Form"]';
        this.SUPPLIEDBY = '//div[text()="Supplied By"]';
        this.PACKAGETYPE = '//div[text()="Package Type"]';
        this.FCC_GRADE = '//span[@class="count"]/parent::a[contains(text(),"FCC")]';
        this.PRODUCT_CATALOG_BREADCRUMB = '.breadcrumbs [class^="item category"]';
        this.FIRST_PRODUCT_NAME = '.product-item-link.product-name';
        this.FIRST_FILTER = '(//div[@class="filter-options-title"])[1]';
        this.FIRST_FILTERTYPE = '.filter-options-item.allow.active .item.custom-checkbox:nth-child(1) .label';
        this.SELECTED_FILTER_NAME = '//div[@class="amshopby-filter-value"][contains(text(),"%s")]';
        this.REMOVE_SELECTED_FILTER = '.amshopby-filter-current.filter-current .amshopby-remove';
        this.REQUEST_QUOTE_LOGIN = '.action.request_quote.button.button--alt.request-quote';
        this.REQUEST_QUOTE_LOGIN_EMEA = 'button.action.request_quote.button.button--alt.request-quote';
        this.OPEN_FILTER = '.filter-options-item.allow.active';
        this.PRODUCT_CARD = '.item.product.product-item';
        this.PRODUCT_CARD_PRICE = '.price';
        this.PACKAGE_WEIGHT = '#pack_size';
        this.QUANTITY = '#quantity';
        this.POTENTIAL_VOLUME = '#potential_volume';
        this.APPLICATION = '#application';
        this.ALREADY_YES = '#already-yes';
        this.ALREADY_NO = '#already-no';
        this.TECH_YES = '#tech-yes';
        this.TECH_NO = '#tech-no';
        this.WEB_PRICE_TAG = '.pricing-box.pricing-box__web-price';
        this.FILTER_OPTIONS = '[class="filter-options-item"]';
        this.FILTER_TITLE = '.filter-options-title';
        this.FILTER_TYPE_CHECKBOX = '.item.custom-checkbox span.label';
        this.SELECTED_FILTERS = '.item.amshopby-item';
        this.CLEAR_ALL_FILTERS = 'a.reset-filters'
    }
}
module.exports = new ProductCatlogPage_Locator();
