class SignUpPageEmea_Locator{
    constructor(){
    /*  NEW CREDIT APPLICATION FORM EMEA
    Contact Information Page 1          */
    this.COMPANY_FIELD_CREDIT_APPL = '[id="contact-step"] [id="company"]';
    this.COMPANY_REGISTRATION_NUMBER = '[id="contact-step"] [id="registration_number"]';
    this.DATE_PICKER = '[id="contact-step"] [id="registration_date"]';
    this.VAT_NUMBER = '[id="contact-step"] [id="vat_number"]';
    this.PHONE_NUMBER_FIELD_CREDIT_APPL ='[id="contact-step"] [id="main_telephone"]';
    this.EMAIL_INVOICES = '[id="contact-step"] [id="invoice_email"]';
    this.CREDIT_APPL_CANCEL_BUTTON_ = '[class="contact-info__actions"] [class="cancel-link"]';
    this.CREDIT_APPL_BACK_BUTTON = '[class="contact-info__actions"] [class="company-back-button"]';
    this.CREDIT_APPL_CONTINUE_BUTTON = '[class="contact-info__actions"] [class="button button--primary button-continue"]';
    this.COMPANY_FIELD_CREDIT_APPL_ERROR = '//*[@id="registration_number-error"]';
    this.COMPANY_REGISTRATION_NUMBER_ERROR = '[id="contact-step"] [id="registration_number-error"]';
    this.DATE_PICKER_ERROR = '//*[contains(@class,"datepicker mage-error")]';
    this.VAT_NUMBER_ERROR = '//*[@id="vat_number-error"]';
    this.PHONE_NUMBER_FIELD_CREDIT_APPL_ERROR = '//div[@id="telephone-error"]';
    this.EMAIL_INVOICES_ERROR = '//*[@id="invoice_email-error"]';
    // Company Addresses Page 2
    this.COUNTRY ='[id="company-addresses"] [id="country"]';
    this.REG_OFFICE_ADDRESS ='[id="company-addresses"] [id="street_1"]';
    this.CITY_FIELD_CREDIT_APPL ='[id="company-addresses"] [name="city"]';
    this.ZIPCODE_CREDIT_APPL = '[id="company-addresses"] [id="zip"]';
    this.INV_BILLING_ADDRESS_CHECKBOX = '[id="company-addresses"] [id="different_billing"]';
    this.INV_BILLING_ADDRESS = '[id="company-addresses"] [id="billing_street"]';
    this.INV_BILLING_ADDRESS_CITY = '[id="company-addresses"] [id="billing_city"]';
    this.INV_BILLING_ZIPCODE = '[id="company-addresses"] [id="billing_zip"]';
    this.TRADING_ADDRESS_CHECKBOX = '[id="company-addresses"] [id="different_trading"]';
    this.TRADING_ADDRESS = '[id="company-addresses"] [id="trading_street"]';
    this.TRADING_ADDRESS_CITY = '[[id="company-addresses"] [id="trading_city"]';
    this.TRADING_ADDRESS_ZIPCODE = '[[id="company-addresses"] [id="trading_zip"]';
    this.COMPANYADDRESS_CANCEL_BUTTON = '[id="company-addresses"] [class="cancel-link"]';
    this.COMPANYADDRESS_BACK_BUTTON = '[id="company-addresses"] [class="company-back-button"]';
    this.COMPANYADDRESS_CONTINUE_BUTTON = '[id="company-addresses"] [class="button button--primary button-continue-company"]';
    this.REG_OFFICE_ADDRESS_ERROR = '[id="company-addresses"] [id="street_1-error"]';
    this.CITY_FIELD_CREDIT_APPL_ERROR = '[id="company-addresses"] [id="city-error"]';
    this.ZIPCODE_CREDIT_APPL_ERROR = '[id="company-addresses"] [id="zip-error"]';
    this.INV_BILLING_ADDRESS_ERROR ='[id="company-addresses"] [id="billing_street-error"]';
    this.INV_BILLING_CITY_ERROR = '[id="company-addresses"] [id="billing_city-error"]';
    this.INV_BILLING_ZIPCODE_ERROR = '[id="company-addresses"] [id="billing_zip-error"]';
    this.TRADING_ADDRESS_ERROR = '[id="company-addresses"] [id="trading_street-error"]';
    this.TRADING_ADDRESS_CITY_ERROR = '[id="company-addresses"] [id="trading_city-error"]';
    this.TRADING_ADDRESS_ZIPCODE_ERROR = '[id="company-addresses"] [id="trading_zip-error"]';
    // Account Contact Details Page 3
    this.PRIMARY_CONTACT_DETAILS_FIRSTNAME = '[id="account-contact-details"] [id="firstname"]';
    this.PRIMARY_CONTACT_DETAILS_LASTNAME = '[id="account-contact-details"] [id="lastname"]';
    this.PRIMARY_CONTACT_DETAILS_JOB_TITLE = '[id="account-contact-details"] [id="title"]';
    this.PRIMARY_CONTACT_DETAILS_EMAIL = '[id="account-contact-details"] [id="email"]';
    this.PRIMARY_CONTACT_DETAILS_PHONE = '[id="account-contact-details"] [id="telephone"]';
    this.ORDER_CONFIRMATION_CHECKBOX = '[id="account-contact-details"] [id="same_order_contact"]';
    this.ORDER_CONFIRMATION_FIRSTNAME = '[id="account-contact-details"] [id="order_firstname"]';
    this.ORDER_CONFIRMATION_LASTNAME = '[id="account-contact-details"] [id="order_lastname"]';
    this.ORDER_CONFIRMATION_PHONE = '[id="account-contact-details"] [id="order_telephone"]';
    this.ORDER_CONFIRMATION_EMAIL= '[id="account-contact-details"] [id="order_email"]';
    this.PRICING_CONTACT_CHECKBOX= '[id="account-contact-details"] [id="same_pricing_contact"]';
    this.SAFETY_DATA_SHEET_CHECKBOX = '[id="account-contact-details"] [id="same_safety_contact"]';
    this.SAFETY_DATA_SHEET_FIRSTNAME = '[id="account-contact-details"] [id="safety_firstname"]';
    this.SAFETY_DATA_SHEET_LASTNAME = '[id="account-contact-details"] [id="safety_lastname"]';
    this.SAFETY_DATA_SHEET_PHONE = '[id="account-contact-details"] [id="safety_telephone"]';
    this.SAFETY_DATA_SHEET_EMAIL = '[id="account-contact-details"] [id="safety_email"]';
    this.PRODUCT_SPECIFICATIONS_CHECKBOX = '[id="account-contact-details"] [id="same_product_contact"]';
    this.PRODUCT_SPECIFICATIONS_FIRSTNAME = '[id="account-contact-details"] [id="product_firstname"]';
    this.PRODUCT_SPECIFICATIONS_LASTNAME = '[id="account-contact-details"] [id="product_lastname"]'
    this.PRODUCT_SPECIFICATIONS_PHONE = '[id="account-contact-details"] [id="product_telephone"]';
    this.PRODUCT_SPECIFICATIONS_EMAIL = '[id="account-contact-details"] [id="product_email"]';
    this.TECHNICAL_CHECKBOX = '[id="account-contact-details"] [id="same_technical_contact"]';
    this.TECHNICAL_FIRSTNAME = '[id="account-contact-details"] [id="technical_firstname"]';
    this.TECHNICAL_LASTNAME = '[id="account-contact-details"] [id="technical_lastname"]';
    this.TECHNICAL_PHONE = '[id="account-contact-details"] [id="technical_telephone"]';
    this.TECHNICAL_EMAIL = '[id="account-contact-details"] [id="technical_email"]';
    this.QUALITY_CHECKBOX = '[id="account-contact-details"] [id="same_quality_contact"]';
    this.QUALITY_FIRSTNAME = '[id="account-contact-details"] [id="quality_firstname"]';
    this.QUALITY_LASTNAME = '[id="account-contact-details"] [id="quality_lastname"]';
    this.QUALITY_PHONE = '[id="account-contact-details"] [id="quality_telephone"]';
    this.QUALITY_EMAIL = '[id="account-contact-details"] [id="quality_email"]';
    this.DELIVERY_NOTES_CHECKBOX = '[id="account-contact-details"] [id="same_delivery_contact"]';
    this.ACCOUNT_PAYABLE_CHECKBOX = '[id="account-contact-details"] [id="same_accounts_payable_contact"]';
    this.ACCOUNT_PAYABLE_FIRSTNAME = '[id="account-contact-details"] [id="accounts_payable_firstname"]';
    this.ACCOUNT_PAYABLE_LASTNAME = '[id="account-contact-details"] [id="accounts_payable_lastname"]';
    this.ACCOUNT_PAYABLE_PHONE = '[id="account-contact-details"] [id="accounts_payable_telephone"]';
    this.ACCOUNT_PAYABLE_EMAIL = '[id="account-contact-details"] [id="accounts_payable_email"]';
    this.ACCOUNT_CONTACT_DETAILS_CANCEL_BUTTON ='[id="account-contact-details"] [class="cancel-link"]';
    this.ACCOUNT_CONTACT_DETAILS_BACK_BUTTON = '[id="account-contact-details"] [class="account-back-button"]';
    this.ACCOUNT_CONTACT_DETAILS_CONTINUE_BUTTON = '[id="account-contact-details"] [class="button button--primary button-continue-account"]';
    this.PRIMARY_CONTACT_DETAILS_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="firstname-error"]';
    this.PRIMARY_CONTACT_DETAILS_LASTNAME_ERROR = '[id="account-contact-details"] [id="lastname-error"]';
    this.PRIMARY_CONTACT_DETAILS_JOB_TITLE_ERROR = '[id="account-contact-details"] [id="title-error"]';
    this.PRIMARY_CONTACT_DETAILS_EMAIL_ERROR = '[id="account-contact-details"] [id="email-error"]';
    this.PRIMARY_CONTACT_DETAILS_PHONE_ERROR = '[id="account-contact-details"] [id="telephone-error"]';
    this.ORDER_CONFIRMATION_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="order_firstname-error"]';
    this.ORDER_CONFIRMATION_LASTNAME_ERROR = '[id="account-contact-details"] [id="order_lastname-error"]';
    this.ORDER_CONFIRMATION_PHONE_ERROR = '[id="account-contact-details"] [id="order_telephone-error"]';
    this.ORDER_CONFIRMATION_EMAIL_ERROR = '[id="account-contact-details"] [id="order_email-error"]';
    this.SAFETY_DATA_SHEET_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="safety_firstname-error"]';
    this.SAFETY_DATA_SHEET_LASTNAME_ERROR = '[id="account-contact-details"] [id="safety_lastname-error"]';
    this.SAFETY_DATA_SHEET_PHONE_ERROR = '[id="account-contact-details"] [id="safety_telephone-error"]';
    this.SAFETY_DATA_SHEET_EMAIL_ERROR = '[id="account-contact-details"] [id="safety_email-error"]';
    this.PRODUCT_SPECIFICATIONS_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="product_firstname-error"]';
    this.PRODUCT_SPECIFICATIONS_LASTNAME_ERROR = '[id="account-contact-details"] [id="product_lastname-error"]'
    this.PRODUCT_SPECIFICATIONS_PHONE_ERROR = '[id="account-contact-details"] [id="product_telephone-error"]';
    this.PRODUCT_SPECIFICATIONS_EMAIL_ERROR = '[id="account-contact-details"] [id="product_email-error"]';
    this.TECHNICAL_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="technical_firstname-error"]';
    this.TECHNICAL_LASTNAME_ERROR = '[id="account-contact-details"] [id="technical_lastname-error"]';
    this.TECHNICAL_PHONE_ERROR = '[id="account-contact-details"] [id="technical_telephone-error"]';
    this.TECHNICAL_EMAIL_ERROR = '[id="account-contact-details"] [id="technical_email-error"]';
    this.QUALITY_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="quality_firstname-error"]';
    this.QUALITY_LASTNAME_ERROR = '[id="account-contact-details"] [id="quality_lastname-error"]';
    this.QUALITY_PHONE_ERROR = '[id="account-contact-details"] [id="quality_telephone-error"]';
    this.QUALITY_EMAIL_ERROR = '[id="account-contact-details"] [id="quality_email-error"]';
    this.ACCOUNT_PAYABLE_FIRSTNAME_ERROR = '[id="account-contact-details"] [id="accounts_payable_firstname-error"]';
    this.ACCOUNT_PAYABLE_LASTNAME_ERROR = '[id="account-contact-details"] [id="accounts_payable_lastname-error"]';
    this.ACCOUNT_PAYABLE_PHONE_ERROR = '[id="account-contact-details"] [id="accounts_payable_telephone-error"]';
    this.ACCOUNT_PAYABLE_EMAIL_ERROR = '[id="account-contact-details"] [id="accounts_payable_email-error"]';
    // Delivery Point Page 4
    this.DELIVERY_POINT_SHIPTOCOMPANYNAME = '[id="delivery-point"] [name="ship_company"]';
    this.DELIVERY_POINT_CITY = '[id="delivery-point"] [name="ship_city"]';
    this.DELIVERY_POINT_ADDRESS = '[id="delivery-point"] [name="ship_address-line-1"]';
    this.DELIVERY_POINT_ZIPCODE = '[id="delivery-point"] [name="ship_zip"]';
    this.DELIVERY_POINT_CANCEL_BUTTON = '[id="delivery-point"] [class="cancel-link"]';
    this.DELIVERY_POINT_BACK_BUTTON = '[id="delivery-point"] [class="delivery-back-button"]';
    this.DELIVERY_POINT_CONTINUE_BUTTON = '[id="delivery-point"] [class="button button--primary button-continue-delivery"]';
    this.DELIVERY_POINT_SHIPTOCOMPANYNAME_ERROR = '[id="delivery-point"] [id="ship_company-error"]';
    this.DELIVERY_POINT_CITY_ERROR = '[id="delivery-point"] [id="ship_city-error"]';
    this.DELIVERY_POINT_ZIPCODE_ERROR = '[id="delivery-point"] [id="ship_zip-error"]';
    this.DELIVERY_POINT_FORKLIFT_YES_RADIO_BTN = '[id="delivery-point"] [id="yes_forklift"]';
    this.DELIVERY_POINT_LOAD_CAPACITY = '[id="delivery-point"] [name="load_capacity"]';
    this.ARTICULATED_VEHICLES_YES_RADIO_BTN = '#yes_articulated_vehicles';
    // Delivery Point Contact Details Page 5
    this.DELIVERY_SAFE_DATA_SHEETS_CHECKBOX ='[id="delivery-point-contact-details"] [id="same_delivery_safety_contact"]';
    this.DELIVERY_SAFE_DATA_SHEETS_FIRSTNAME = '[id="delivery-point-contact-details"] [id="delivery_safety_firstname"]';
    this.DELIVERY_SAFE_DATA_SHEETS_LASTNAME = '[id="delivery-point-contact-details"] [id="delivery_safety_lastname"]';
    this.DELIVERY_SAFE_DATA_SHEETS_EMAIL = '[id="delivery-point-contact-details"] [id="delivery_safety_email"]';
    this.PS_TECHNICAL_DATA_SHEETS_CHECKBOX ='[id="delivery-point-contact-details"] [id="same_delivery_technical_contact"]';
    this.PS_TECHNICAL_DATA_SHEETS_FIRSTNAME = '[id="delivery-point-contact-details"] [id="delivery_technical_firstname"]';
    this.PS_TECHNICAL_DATA_SHEETS_LASTNAME = '[id="delivery-point-contact-details"] [id="delivery_technical_lastname"]';
    this.PS_TECHNICAL_DATA_SHEETS_EMAIL = '[id="delivery-point-contact-details"] [id="delivery_technical_email"]';
    this.QUALITY_DEPARTMENT_CHECKBOX = '[id="delivery-point-contact-details"] [id="same_delivery_quality_contact"]';
    this.QUALITY_DEPARTMENT_SHEETS_FIRSTNAME = '[id="delivery-point-contact-details"] [id="delivery_quality_firstname"]';
    this.QUALITY_DEPARTMENT_SHEETS_LASTNAME = '[id="delivery-point-contact-details"] [id="delivery_quality_lastname"]';
    this.QUALITY_DEPARTMENT_EMAIL = '[id="delivery-point-contact-details"] [id="delivery_quality_email"]';
    this.DP_CONTACT_DETAILS_CANCEL_BUTTON = '[id="delivery-point-contact-details"] [class="cancel-link"]';
    this.DP_CONTACT_DETAILS_BACK_BUTTON = '[id="delivery-point-contact-details"] [class="delivery-point-back-button"]';
    this.DP_CONTACT_DETAILS_CONTINUE_BUTTON = '[id="delivery-point-contact-details"] [class="button button--primary button-continue-delivery-point"]';
    this.DELIVERY_SAFE_DATA_SHEETS_FIRSTNAME_ERROR = '[id="delivery-point-contact-details"] [id="delivery_safety_firstname-error"]';
    this.DELIVERY_SAFE_DATA_SHEETS_LASTNAME_ERROR = '[id="delivery-point-contact-details"] [id="delivery_safety_lastname-error"]';
    this.DELIVERY_SAFE_DATA_SHEETS_EMAIL_ERROR = '[id="delivery-point-contact-details"] [id="delivery_safety_email-error"]';
    this.PS_TECHNICAL_DATA_SHEETS_FIRSTNAME_ERROR = '[id="delivery-point-contact-details"] [id="delivery_technical_firstname-error"]';
    this.PS_TECHNICAL_DATA_SHEETS_LASTNAME_ERROR = '[id="delivery-point-contact-details"] [id="delivery_technical_lastname-error"]';
    this.PS_TECHNICAL_DATA_SHEETS_EMAIL_ERROR = '[id="delivery-point-contact-details"] [id="delivery_technical_email-error"]';
    this.QUALITY_DEPARTMENT_SHEETS_FIRSTNAME_ERROR= '[id="delivery-point-contact-details"] [id="delivery_quality_firstname-error"]';
    this.QUALITY_DEPARTMENT_SHEETS_LASTNAME_ERROR = '[id="delivery-point-contact-details"] [id="delivery_quality_lastname-error"]';
    this.QUALITY_DEPARTMENT_EMAIL_ERROR = '[id="delivery-point-contact-details"] [id="delivery_quality_email-error"]';
    // Customer Declaration Page 6
    this.CUSTOMER_DECLARATION_FIRSTNAME = '[id="customer-declaration"] [id="permission_firstname"]';
    this.CUSTOMER_DECLARATION_LASTNAME = '[id="customer-declaration"] [id="permission_lastname"]';
    this.CUSTOMER_DECLARATION_JOB_TITLE = '[id="customer-declaration"] [id="job_title"]';
    this.CUSTOMER_DECLARATION_PHONE = '[id="customer-declaration"] [id="permission_telephone"]';
    this.CUSTOMER_DECLARATION_EMAIL = '[id="customer-declaration"] [id="permission_email"]';
    this.CUSTOMER_DECLARATION_SIGNATURE = '[id="customer-declaration"] [id="signature"]';
    this.CUSTOMER_DECLARATION_DATE = '[id="customer-declaration"] [id="permission_date"]';
    this.CUSTOMER_DECLARATION_AGREE_CHECKBOX = '[id="customer-declaration"] [id="terms-conditions"]';
    this.CUSTOMER_DECLARATION_READ_CHECKBOX ='[id="customer-declaration"] [id="privacy-policy"]';
    this.CUSTOMER_DECLARATION_CANCEL_BUTTON ='[id="customer-declaration"] [class="cancel-link"]';
    this.CUSTOMER_DECLARATION_BACK_BUTTON ='[id="customer-declaration"] [class="customer-back-button"]';
    this.CUSTOMER_DECLARATION_SUBMIT_BUTTON ='[id="customer-declaration"] [class="button button--primary button-continue-customer"]';
    this.CUSTOMER_DECLARATION_FIRSTNAME_ERROR = '[id="customer-declaration"] [id="permission_firstname-error"]';
    this.CUSTOMER_DECLARATION_LASTNAME_ERROR = '[id="customer-declaration"] [id="permission_lastname-error"]';
    this.CUSTOMER_DECLARATION_JOB_TITLE_ERROR = '[id="customer-declaration"] [id="job_title-error"]';
    this.CUSTOMER_DECLARATION_PHONE_ERROR = '[id="customer-declaration"] [id="permission_telephone-error"]';
    this.CUSTOMER_DECLARATION_EMAIL_ERROR = '[id="customer-declaration"] [id="permission_email-error"]';
    this.CUSTOMER_DECLARATION_SIGNATURE_ERROR = '[id="customer-declaration"] [id="signature-error"]';
    this.CUSTOMER_DECLARATION_AGREE_CHECKBOX_ERROR = '[id="customer-declaration"] [id="ach[terms_conditions]-error"]';
    this.CUSTOMER_DECLARATION_READ_CHECKBOX_ERROR ='[id="customer-declaration"] [id="ach[privacy-policy]-error"]';
    }
}
module.exports = new SignUpPageEmea_Locator();
